version: '3.8'

services:
  my-postgress-database:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nestjs-app
    ports:
      - "3001:3000"
    depends_on:
      - my-postgress-database
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
volumes:
  postgres-data:
 